apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80
    env:
    - name: PROP1
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: PROP1
